### ISSUE TITLE
Setup discord applcation

### ISSUE THREAD

**Issue by meatball133** [meatball133/nimble-neutrinos#13]
We need a base structure to build our discord application on. This includes:

- File structure 
- Structure to allowed to integrate other commands/functions
- A version command which can for now just print a basic string.
- A system to connect the system to the discord api including inserting token

⚠️ **DO NOT SEND THE TOKEN IN THE PULL REQUEST** ⚠️

**Comment by GetPsyched** [comment]
I have a boilerplate for this; we shouldn't copy it, but it might be a good starting point:
https://github.com/GetPsyched/dpy-boilerplate
